# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lar2019/project/AppliedRoboticsStudentInterface

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lar2019/project/AppliedRoboticsStudentInterface

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lar2019/project/AppliedRoboticsStudentInterface/CMakeFiles /home/lar2019/project/AppliedRoboticsStudentInterface/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lar2019/project/AppliedRoboticsStudentInterface/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named student

# Build rule for target.
student: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 student
.PHONY : student

# fast build rule for target.
student/fast:
	$(MAKE) -f CMakeFiles/student.dir/build.make CMakeFiles/student.dir/build
.PHONY : student/fast

#=============================================================================
# Target rules for targets named calibrate

# Build rule for target.
calibrate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 calibrate
.PHONY : calibrate

# fast build rule for target.
calibrate/fast:
	$(MAKE) -f CMakeFiles/calibrate.dir/build.make CMakeFiles/calibrate.dir/build
.PHONY : calibrate/fast

src/camera_calibration.o: src/camera_calibration.cpp.o

.PHONY : src/camera_calibration.o

# target to build an object file
src/camera_calibration.cpp.o:
	$(MAKE) -f CMakeFiles/calibrate.dir/build.make CMakeFiles/calibrate.dir/src/camera_calibration.cpp.o
.PHONY : src/camera_calibration.cpp.o

src/camera_calibration.i: src/camera_calibration.cpp.i

.PHONY : src/camera_calibration.i

# target to preprocess a source file
src/camera_calibration.cpp.i:
	$(MAKE) -f CMakeFiles/calibrate.dir/build.make CMakeFiles/calibrate.dir/src/camera_calibration.cpp.i
.PHONY : src/camera_calibration.cpp.i

src/camera_calibration.s: src/camera_calibration.cpp.s

.PHONY : src/camera_calibration.s

# target to generate assembly for a file
src/camera_calibration.cpp.s:
	$(MAKE) -f CMakeFiles/calibrate.dir/build.make CMakeFiles/calibrate.dir/src/camera_calibration.cpp.s
.PHONY : src/camera_calibration.cpp.s

src/find_robot.o: src/find_robot.cpp.o

.PHONY : src/find_robot.o

# target to build an object file
src/find_robot.cpp.o:
	$(MAKE) -f CMakeFiles/student.dir/build.make CMakeFiles/student.dir/src/find_robot.cpp.o
.PHONY : src/find_robot.cpp.o

src/find_robot.i: src/find_robot.cpp.i

.PHONY : src/find_robot.i

# target to preprocess a source file
src/find_robot.cpp.i:
	$(MAKE) -f CMakeFiles/student.dir/build.make CMakeFiles/student.dir/src/find_robot.cpp.i
.PHONY : src/find_robot.cpp.i

src/find_robot.s: src/find_robot.cpp.s

.PHONY : src/find_robot.s

# target to generate assembly for a file
src/find_robot.cpp.s:
	$(MAKE) -f CMakeFiles/student.dir/build.make CMakeFiles/student.dir/src/find_robot.cpp.s
.PHONY : src/find_robot.cpp.s

src/process_arena.o: src/process_arena.cpp.o

.PHONY : src/process_arena.o

# target to build an object file
src/process_arena.cpp.o:
	$(MAKE) -f CMakeFiles/student.dir/build.make CMakeFiles/student.dir/src/process_arena.cpp.o
.PHONY : src/process_arena.cpp.o

src/process_arena.i: src/process_arena.cpp.i

.PHONY : src/process_arena.i

# target to preprocess a source file
src/process_arena.cpp.i:
	$(MAKE) -f CMakeFiles/student.dir/build.make CMakeFiles/student.dir/src/process_arena.cpp.i
.PHONY : src/process_arena.cpp.i

src/process_arena.s: src/process_arena.cpp.s

.PHONY : src/process_arena.s

# target to generate assembly for a file
src/process_arena.cpp.s:
	$(MAKE) -f CMakeFiles/student.dir/build.make CMakeFiles/student.dir/src/process_arena.cpp.s
.PHONY : src/process_arena.cpp.s

src/student_interface.o: src/student_interface.cpp.o

.PHONY : src/student_interface.o

# target to build an object file
src/student_interface.cpp.o:
	$(MAKE) -f CMakeFiles/student.dir/build.make CMakeFiles/student.dir/src/student_interface.cpp.o
.PHONY : src/student_interface.cpp.o

src/student_interface.i: src/student_interface.cpp.i

.PHONY : src/student_interface.i

# target to preprocess a source file
src/student_interface.cpp.i:
	$(MAKE) -f CMakeFiles/student.dir/build.make CMakeFiles/student.dir/src/student_interface.cpp.i
.PHONY : src/student_interface.cpp.i

src/student_interface.s: src/student_interface.cpp.s

.PHONY : src/student_interface.s

# target to generate assembly for a file
src/student_interface.cpp.s:
	$(MAKE) -f CMakeFiles/student.dir/build.make CMakeFiles/student.dir/src/student_interface.cpp.s
.PHONY : src/student_interface.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... student"
	@echo "... calibrate"
	@echo "... src/camera_calibration.o"
	@echo "... src/camera_calibration.i"
	@echo "... src/camera_calibration.s"
	@echo "... src/find_robot.o"
	@echo "... src/find_robot.i"
	@echo "... src/find_robot.s"
	@echo "... src/process_arena.o"
	@echo "... src/process_arena.i"
	@echo "... src/process_arena.s"
	@echo "... src/student_interface.o"
	@echo "... src/student_interface.i"
	@echo "... src/student_interface.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

